name: WakaTime status update

on:
  # push:
  #   branches: [main]
  # schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    # - cron: "1 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: mathewbushuru/mathew-wakatime-github-action@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          # Range of fetching data - default is "last_7_days". 
          STATS_RANGE: "last_7_days"
